services:

  api:
    image: marins14/locadora-api:1.0
    environment:
    # NÃO ESQUEÇA DE SUBSTITUIR OS VALORES ANTES DE INICIAR
      POSTGRES_DB: <NOME_DO_DB>
      POSTGRES_USER: <USER_DB>
      POSTGRES_PASSWORD: <PASSWD_DB>
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_DB: <NOME_DO_DB>
      POSTGRES_USER: <USER_DB>
      POSTGRES_PASSWORD: <PASSWD_DB>
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5499:5432"
    volumes:
      - postgres_locadora:/var/lib/postgresql/data

volumes:
  postgres_locadora:
    name: projeto_locadora